version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: compose.Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/tickets/src
      - ./user:/tickets/user
      - ./logs:/tickets/logs
      - ./.env:/tickets/.env:ro
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tickets
      - DB_USER=tickets
      - DB_PASS=tickets
      - DB_TABLE_PREFIX=dsctickets_
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - "MYSQL_DATABASE=tickets"
      - "MYSQL_USER=tickets"
      - "MYSQL_PASSWORD=tickets"

      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
