blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/discord-tickets/bot/discussions
    about: Request new features, share ideas and guides, ask for help, or just talk.
  - name: Discord support server
    url: https://go.eartharoid.me/discord
    about: The best place to go for help installing or using DiscordTickets
