#####################################################
##  ____                                        _  ##
## |  _ \  (_)  ___    ___    ___    _ __    __| | ##
## | | | | | | / __|  / __|  / _ \  | '__|  / _` | ##
## | |_| | | | \__ \ | (__  | (_) | | |    | (_| | ##
## |____/  |_| |___/  \___|  \___/  |_|     \__,_| ##
##   _____              _             _            ##
##  |_   _| (_)   ___  | | __   ___  | |_   ___    ##
##    | |   | |  / __| | |/ /  / _ \ | __| / __|   ##
##    | |   | | | (__  |   <  |  __/ | |_  \__ \   ##
##    |_|   |_|  \___| |_|\_\  \___|  \__| |___/   ##
##                                                 ##
##    Documentation: https://discordtickets.app    ##
##    Support:        https://lnk.earth/discord    ##
#####################################################

logs:
  files:
    directory: ./logs
    enabled: true
    keepFor: 30 # days
  level: info # debug|verbose|info|success|warn|notice|error|critical
presence:
  activities:
    - name: /new
    - name: with {totalTickets} tickets
    - name: '{openTickets} tickets'
      type: 3 # https://discord-api-types.dev/api/discord-api-types-v10/enum/ActivityType
    - name: '{avgResponseTime} response time'
      type: 3
  interval: 20 # seconds, only used if activities.length > 1
  status: online # online|idle|invisible|dnd
overrides:
  disableArchives: false
stats: true