#####################################################
##  ____                                        _  ##
## |  _ \  (_)  ___    ___    ___    _ __    __| | ##
## | | | | | | / __|  / __|  / _ \  | '__|  / _` | ##
## | |_| | | | \__ \ | (__  | (_) | | |    | (_| | ##
## |____/  |_| |___/  \___|  \___/  |_|     \__,_| ##
##   _____              _             _            ##
##  |_   _| (_)   ___  | | __   ___  | |_   ___    ##
##    | |   | |  / __| | |/ /  / _ \ | __| / __|   ##
##    | |   | | | (__  |   <  |  __/ | |_  \__ \   ##
##    |_|   |_|  \___| |_|\_\  \___|  \__| |___/   ##
##                                                 ##
##    Documentation: https://discordtickets.app    ##
##    Support: https://go.eartharoid.me/discord    ##
#####################################################

logs:
  files:
    enabled: true
    keepFor: 30 # days
    split: true # split stdout (info) and stderr (warnings & errors) into separate files? 
  level: info